async (page) => {
  const checks = [], errors = [], writes = [], screenshots = [];
  const assert = (ok, name) => { if (!ok) throw new Error(name); checks.push(name); };
  const click = name => page.getByRole('button', { name, exact: true }).click();
  const dialog = name => page.getByRole('dialog', { name, exact: true });
  const selectNode = title => page.locator('.wb-node').filter({ has: page.locator('strong', { hasText: new RegExp('^' + title + '$') }) }).click();
  const readRun = () => page.evaluate(() => Data.workbenchGet('/ledger').then(async value => Data.workbenchGet('/runs/' + value.runs[0].id)));
  const waitRun = async predicate => {
    for (let attempt = 0; attempt < 90; attempt++) {
      const rows = await page.evaluate(() => Data.workbenchGet('/ledger'));
      const value = rows.runs.length ? await readRun() : null;
      if (value && predicate(value)) return value;
      await page.waitForTimeout(1000);
    }
    throw new Error('실제 실행 상태를 기다리는 시간이 초과됐습니다.');
  };
  const screenshot = async name => { const file = `output/playwright/workbench-evidence-${name}.png`; await page.screenshot({ path: file, fullPage: true, animations: 'disabled' }); screenshots.push(file); };
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.method() === 'POST') writes.push(new URL(request.url()).pathname); });
  assert(new URL(page.url()).host === '127.0.0.1:8798', '격리 localhost 미리보기만 검사');
  await page.evaluate(() => { ['studio.workbench.draft.v1', 'studio.workbench.lastRun', 'studio.workbench.surface.v1'].forEach(k => localStorage.removeItem(k)); });
  await page.reload(); await page.setViewportSize({ width: 1536, height: 1140 });
  await page.waitForFunction(() => typeof Data !== 'undefined' && Data.loaded);
  if (await page.locator('#workbench-screen').isHidden()) await page.locator('.bd-nav').getByRole('button', { name: '기능 작업대', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.wb-node').length === 3);
  assert(await page.evaluate(() => Data.get().studio.fake === true), '기존 FakeRuntime 확인 · 실제 모델 없음');
  assert(await page.locator('.wb-drawer').isHidden(), '기능 도구함은 필요할 때만 표시');
  await click('기능 도구함');
  assert(await page.locator('.wb-drawer').isVisible(), '도구함 열기');
  await page.keyboard.press('Escape');
  assert(await page.locator('.wb-drawer').isHidden(), 'Escape로 도구함 닫기');
  assert(await page.getByRole('button', { name: '기능 도구함', exact: true }).evaluate(el => document.activeElement === el), '도구함 닫기 뒤 초점 복귀');
  await click('구현 묶음');
  if (await dialog('작성 중인 흐름 바꾸기').count()) await dialog('작성 중인 흐름 바꾸기').getByRole('button', { name: '바꾸기', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.wb-node').length === 6);
  await page.getByRole('textbox', { name: '작업 묶음 이름', exact: true }).fill('정답과 계약 파일 검증');
  await selectNode('입력 노트');
  await page.getByRole('textbox', { name: '실행 입력', exact: true }).fill('정답 42를 docs/answer.txt에 저장해 주세요.');
  await selectNode('구현');
  await page.getByRole('textbox', { name: '수용 기준 (한 줄에 하나)' }).fill('정답은 42\n계약 파일이 존재한다');
  await click('기준별 완료 근거 지정');
  const proof = dialog('기준별 완료 근거');
  await proof.getByRole('textbox', { name: 'A1 신뢰 검사 이름' }).fill('answer_is_42');
  await proof.getByRole('textbox', { name: 'A1 필수 파일 경로' }).fill('docs/answer.txt');
  await proof.getByRole('textbox', { name: 'A2 필수 파일 경로' }).fill('docs/contract.txt');
  const buttons = proof.locator('button');
  await buttons.last().focus(); await page.keyboard.press('Tab');
  assert(await buttons.first().evaluate(el => document.activeElement === el), '근거 편집 Tab 초점 순환');
  await page.keyboard.press('Shift+Tab');
  assert(await buttons.last().evaluate(el => document.activeElement === el), '근거 편집 Shift+Tab 순환');
  await proof.getByRole('button', { name: '근거 저장', exact: true }).dblclick();
  await page.waitForFunction(() => !document.querySelector('dialog'));
  await page.getByRole('button', { name: '서랍에 저장', exact: true }).dblclick();
  await page.waitForFunction(() => document.querySelector('.wb-save-state')?.textContent.includes('저장된'));
  assert(writes.filter(path => path === '/api/workbench/flows').length === 1, '업무 묶음 저장 중복 클릭 방지');
  await click('접어 보관');
  assert(await page.locator('.wb-layout').isHidden(), '접으면 넓은 작업면 대신 보관 폴더 표시');
  assert(await page.getByRole('button', { name: '정답과 계약 파일 검증 업무 펼치기' }).count() === 1, '같은 저장 묶음 한 개 보존');
  await screenshot('folders');
  await page.reload();
  await page.waitForFunction(() => Data.loaded);
  if (await page.locator('#workbench-screen').isHidden()) await page.locator('.bd-nav').getByRole('button', { name: '기능 작업대', exact: true }).click();
  await page.getByRole('button', { name: '정답과 계약 파일 검증 업무 펼치기' }).waitFor();
  assert(await page.locator('.wb-layout').isHidden(), '보관 상태를 새로고침 뒤 복원');
  await page.getByRole('button', { name: '정답과 계약 파일 검증 업무 펼치기' }).dblclick();
  await page.waitForFunction(() => !document.querySelector('.wb-layout').hidden);
  assert(await page.locator('.wb-node').count() === 6, '폴더에서 저장한 여섯 노드 펼침');
  await selectNode('구현');
  await click('기준별 완료 근거 지정');
  assert(await dialog('기준별 완료 근거').getByRole('textbox', { name: 'A2 필수 파일 경로' }).inputValue() === 'docs/contract.txt', '완료 근거 저장·불러오기');
  await dialog('기준별 완료 근거').getByRole('button', { name: '취소', exact: true }).click();
  await click('상세 접기');
  assert(await page.locator('.wb-detail').isHidden(), '선택 노드의 상세만 접기');
  const inputNode = page.locator('.wb-node').filter({ has: page.locator('strong', { hasText: /^입력 노트$/ }) });
  await inputNode.focus(); const left = await inputNode.evaluate(el => el.offsetLeft);
  await page.keyboard.press('ArrowRight');
  assert(await inputNode.evaluate(el => el.offsetLeft) === left + 20, '키보드로 노드 이동');
  await page.keyboard.press('Enter');
  assert(await page.locator('.wb-detail').isVisible(), 'Enter로 노드 옆 상세 펼침');
  const overlap = await page.locator('.wb-canvas').evaluate(canvas => {
    const pane = canvas.querySelector('.wb-detail').getBoundingClientRect();
    return [...canvas.querySelectorAll('.wb-node')].some(el => { const r = el.getBoundingClientRect(); return r.left < pane.right && r.right > pane.left && r.top < pane.bottom && r.bottom > pane.top; });
  });
  assert(!overlap, '펼친 상세가 이웃 노드 조작을 가리지 않음');
  await page.getByRole('button', { name: '서랍에 저장', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.wb-save-state')?.textContent.includes('저장된 v2'));
  await click('실행 계획 확인');
  const plan = dialog('실행 전 계획 확인');
  assert(await plan.getByRole('button', { name: '확인한 계획 실행' }).isDisabled(), '계획·모델 확인 전 실행 잠금');
  await plan.getByRole('checkbox').nth(0).check(); await plan.getByRole('checkbox').nth(1).check();
  await plan.getByRole('button', { name: '확인한 계획 실행' }).dblclick();
  await waitRun(r => r.status === 'blocked' && Object.values(r.current_tasks || {}).some(t => t.status === 'awaiting_approval'));
  let run = await readRun(); const build = run.snapshot.graph.nodes.find(n => n.definition.spec.operation === 'implement');
  const taskId = run.nodes[build.id].task, oldCandidate = run.current_tasks[taskId].candidate_sha;
  assert(writes.filter(path => path === '/api/workbench/start').length === 1, '중복 실행은 같은 요청 한 번만 제출');
  assert(run.current_tasks[taskId].status === 'awaiting_approval', '누락 후보도 기존 결재에서 근거 확인 가능');
  assert(run.current_tasks[taskId].evidence.items[0].status === 'verified' && run.current_tasks[taskId].evidence.items[1].status === 'missing', '기준별 충족/누락을 실제 증거로 구분');
  await selectNode('테스트');
  await page.waitForFunction(() => document.querySelectorAll('.wb-proof-items > .verified').length === 1 && document.querySelectorAll('.wb-proof-items > .missing').length === 1);
  assert(await page.locator('.wb-proof-items > .verified').count() === 1 && await page.locator('.wb-proof-items > .missing').count() === 1, '청록 충족·주황 누락 표시');
  assert(await page.getByRole('button', { name: '기존 결재 창에서 승인', exact: true }).isDisabled(), '필수 파일 누락 시 승인 버튼 비활성');
  assert((await page.locator('.wb-approval-reasons').textContent()).includes('계약 파일'), '승인 불가 이유 표시');
  await screenshot('missing');
  await click('접어 보관');
  assert((await readRun()).id === run.id && (await readRun()).current_tasks[taskId].status === 'awaiting_approval', '실행 중 업무 접기는 작업·결재를 취소하지 않음');
  await click('펼친 업무');
  await selectNode('테스트');
  await click('작업·일지·산출물 보기');
  await page.getByRole('button', { name: '승인', exact: true }).waitFor();
  assert(await page.getByRole('button', { name: '승인', exact: true }).isDisabled(), '기존 결재 창에서도 누락 승인 잠금');
  await click('수정 요청');
  await page.locator('#layer-popup textarea').fill('계약파일을 추가해 주세요. 정답 42는 유지하세요.');
  await page.getByRole('dialog', { name: '수정 요청', exact: true }).getByRole('button', { name: '보내기', exact: true }).click();
  await page.goto('http://127.0.0.1:8798/#view=workbench');
  await page.locator('.bd-nav').getByRole('button', { name: '기능 작업대', exact: true }).click();
  await waitRun(r => r.revision === 2 && r.status === 'waiting');
  await page.locator('.wb-run-history > summary').click();
  await page.locator(`.wb-run[data-run="${run.id}"]`).click();
  run = await readRun();
  assert(run.current_tasks[taskId].candidate_sha !== oldCandidate, '수정 요청 뒤 새 후보 생성');
  assert(run.current_tasks[taskId].evidence.complete && run.current_tasks[taskId].approval.allowed, '최신 후보의 모든 기준 근거 확인');
  assert(run.versions.length === 1 && run.versions[0].candidate_sha === oldCandidate, '이전 후보와 노드 결과를 별도 보존');
  assert(run.usage.total === 4 && run.usage.current === 2 && run.usage.previous === 2, '최신/이전/전체 호출 집계 일치');
  const qa = run.snapshot.graph.nodes.find(n => n.definition.spec.operation === 'test');
  assert(run.nodes[qa.id].output.candidate_sha === run.current_tasks[taskId].candidate_sha, '장부 테스트 노드도 최신 후보로 갱신');
  await selectNode('테스트');
  assert(await page.getByRole('button', { name: '기존 결재 창에서 승인', exact: true }).isEnabled(), '근거 충족 뒤 승인 버튼 활성');
  await screenshot('latest');
  await page.locator('.wb-version-history > summary').click();
  assert((await page.locator('.wb-version-history').textContent()).includes(oldCandidate.slice(0, 10)), '묶음에 붙은 이전 버전 이력 조회');
  for (const [width, height] of [[1024, 900], [390, 844]]) {
    await page.setViewportSize({ width, height });
    await selectNode('테스트');
    const geometry = await page.locator('#workbench-screen').evaluate(el => ({ width: el.clientWidth, scroll: el.scrollWidth }));
    assert(geometry.scroll <= geometry.width + 1, `${width}px 화면 바깥 가로 넘침 없음`);
  }
  await screenshot('small');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert(await page.locator('.wb-detail').evaluate(el => getComputedStyle(el).animationName === 'none'), 'reduced-motion에서 펼침 애니메이션 제거');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.setViewportSize({ width: 1536, height: 1140 });
  assert(errors.length === 0, '브라우저 런타임 오류 없음');
  return { status: 'pass', phase: 'ready_for_tampered_evidence_check', count: checks.length, checks, errors, writes, screenshots,
    run: run.id, task: taskId, qa_id: run.current_tasks[taskId].qa.qa_id, old_candidate: oldCandidate,
    candidate: run.current_tasks[taskId].candidate_sha, real_model_calls: 0, production_writes: 0 };
}
