async (page) => {
  const checks = [], errors = [], writes = [], geometry = [], screenshots = [];
  const assert = (ok, name) => { if (!ok) throw new Error(name); checks.push(name); };
  const click = name => page.getByRole('button', { name, exact: true }).click();
  const dialog = name => page.getByRole('dialog', { name, exact: true });
  const drawer = async (open = true) => { if ((await page.locator('.wb-drawer').isVisible()) !== open) await click('기능 도구함'); };
  const chooseNode = async title => { await drawer(false); await page.locator('.wb-node').filter({ has: page.locator('strong', { hasText: new RegExp('^' + title + '$') }) }).click(); };
  const readRun = () => page.evaluate(() => Data.workbenchGet('/ledger').then(async x => Data.workbenchGet('/runs/' + x.runs[0].id)));
  const replace = async name => { await click(name); const d = dialog('작성 중인 흐름 바꾸기'); if (await d.count()) await d.getByRole('button', { name: '바꾸기', exact: true }).click(); };
  const screenshot = async name => { const path = 'output/playwright/workbench-evidence-regression-' + name + '.png'; await page.screenshot({ path, fullPage: true, animations: 'disabled' }); screenshots.push(path); };
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (r.method() === 'POST') writes.push(new URL(r.url()).pathname); });
  assert(new URL(page.url()).host === '127.0.0.1:8798', '임시 회사에서만 검사');
  await page.unrouteAll();
  await page.evaluate(() => { ['studio.workbench.draft.v1', 'studio.workbench.lastRun', 'studio.workbench.surface.v1'].forEach(k => localStorage.removeItem(k)); });
  await page.reload();
  await page.setViewportSize({ width: 1536, height: 960 });
  await page.waitForFunction(() => typeof Data !== 'undefined' && Data.loaded);
  if (await page.locator('#workbench-screen').isHidden()) await page.locator('.bd-nav').getByRole('button', { name: '기능 작업대', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.wb-node').length === 3);
  assert(await page.evaluate(() => Data.get().studio.fake === true), '기존 가짜 실행기 확인 · 실제 모델 없음');
  assert(await page.locator('.wb-scope select option').count() === 2, '처음 데이터 로딩 후 프로젝트 목록 표시');
  assert(await page.locator('.wb-scope textarea').inputValue() === 'docs/**', '기존 허용 범위 표시');
  await drawer();
  assert(await page.getByRole('button', { name: '자유 코드·셸 꺼내기' }).isDisabled(), '임의 코드 실행은 이유와 함께 비활성화');
  await click('실행 계획 확인');
  await page.locator('.wb-message').filter({ hasText: '실행 입력' }).waitFor();
  assert(await page.getByRole('dialog').count() === 0, '빈 실행 입력 거부');

  await click('+ 폴더');
  await dialog('새 폴더').getByRole('textbox', { name: '폴더 이름' }).fill('반복 업무');
  await dialog('새 폴더').getByRole('button', { name: '저장', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('dialog'));
  assert((await page.locator('.wb-drawer select').textContent()).includes('반복 업무'), '폴더 생성');
  await click('이름 변경');
  await dialog('폴더 이름 변경').getByRole('textbox').fill('정리 서랍');
  await dialog('폴더 이름 변경').getByRole('button', { name: '저장', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('dialog'));
  assert((await page.locator('.wb-drawer select').textContent()).includes('정리 서랍'), '폴더 이름 편집');
  await click('+ 노트');
  const note = dialog('새 기능 노트');
  await note.getByRole('textbox', { name: '기능 제목' }).fill('반복 문장 노트');
  const folderId = await page.locator('.wb-drawer select').inputValue();
  await note.getByRole('combobox', { name: '폴더' }).selectOption(folderId);
  await note.getByRole('textbox', { name: '목적', exact: true }).fill('보고서 머리말을 반복해서 정리');
  await note.getByRole('textbox', { name: '입력 설명' }).fill('줄별 업무 목록');
  await note.getByRole('textbox', { name: '출력 설명' }).fill('머리말이 붙은 글');
  await note.getByRole('textbox', { name: '주의', exact: true }).fill('검토 후 사용');
  await note.getByRole('textbox', { name: '예시·참고 코드' }).fill('<img src=x onerror="window.noteExecuted=1">; arbitrary shell code');
  await note.getByRole('textbox', { name: '앞에 붙일 글' }).fill('[정리] ');
  for (const key of ['Tab', 'Shift+Tab']) for (let i = 0; i < 30; i++) {
    await page.keyboard.press(key);
    if (!(await note.evaluate(e => e.contains(document.activeElement)))) throw new Error('Dialog focus escaped');
  }
  assert(true, '대화상자 Tab·Shift+Tab 초점 순환');
  await screenshot('note');
  await note.getByRole('button', { name: '기능 저장', exact: true }).dblclick();
  await page.waitForFunction(() => !document.querySelector('dialog'));
  assert(writes.filter(x => x === '/api/workbench/nodes').length === 1, '노트 중복 클릭은 한 번만 저장');
  assert(await page.locator('.wb-library strong').textContent() === '반복 문장 노트', '폴더로 기능 분류');
  await page.getByRole('button', { name: '반복 문장 노트 꺼내기' }).click();
  await page.waitForFunction(() => document.querySelectorAll('.wb-node').length === 4);
  assert(await page.locator('.wb-library').count() === 1, '꺼낸 뒤 원래 기능은 서랍에 남음');
  assert(await page.evaluate(() => !window.noteExecuted && !document.querySelector('.wb-note dd img')), '참고 코드·에이전트 글은 HTML이나 코드로 실행되지 않음');
  const customId = await page.locator('.wb-node[aria-pressed="true"]').getAttribute('data-node');
  const nodeIds = await page.locator('.wb-node').evaluateAll(es => es.map(e => e.dataset.node));
  const [inputId, linesId, summaryId] = nodeIds;
  await drawer(false);
  await page.getByRole('combobox', { name: '출발 노드' }).selectOption(linesId);
  await page.getByRole('combobox', { name: '도착 노드' }).selectOption(customId);
  await click('연결하기');
  await page.waitForFunction(() => document.querySelectorAll('.wb-edge-list li').length === 3);
  assert(await page.locator('.wb-wire').count() === 3, '실제 연결선 그리기');
  await page.getByRole('button', { name: `${inputId}에서 ${linesId} 연결 끊기` }).click();
  await page.waitForFunction(() => document.querySelectorAll('.wb-wire').length === 2);
  await page.getByRole('combobox', { name: '출발 노드' }).selectOption(customId);
  await page.getByRole('combobox', { name: '도착 노드' }).selectOption(linesId);
  await click('연결하기');
  await page.locator('.wb-message').filter({ hasText: '순환' }).waitFor();
  assert(await page.locator('.wb-wire').count() === 2, '순환 연결 거부 · 기존 그래프 보존');
  await page.getByRole('combobox', { name: '출발 노드' }).selectOption(inputId);
  await click('연결하기');
  await page.waitForFunction(() => document.querySelectorAll('.wb-wire').length === 3);
  await page.getByRole('combobox', { name: '출발 노드' }).selectOption(inputId);
  await page.getByRole('combobox', { name: '도착 노드' }).selectOption(linesId);
  await click('연결하기');
  await page.locator('.wb-message').filter({ hasText: '중복' }).waitFor();
  assert(await page.locator('.wb-wire').count() === 3, '중복 입력 연결 거부');
  await drawer();
  await page.locator('.wb-drawer select').selectOption('all');
  await page.getByRole('button', { name: '테스트 꺼내기', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.wb-node').length === 5);
  const testId = await page.locator('.wb-node[aria-pressed="true"]').getAttribute('data-node');
  await drawer(false);
  await page.getByRole('combobox', { name: '출발 노드' }).selectOption(inputId);
  await page.getByRole('combobox', { name: '도착 노드' }).selectOption(testId);
  await click('연결하기');
  await page.locator('.wb-message').filter({ hasText: '형식' }).waitFor();
  assert(await page.locator('.wb-wire').count() === 3, '잘못된 입출력 형식 거부');
  await click('작업대에서 제거');
  await page.waitForFunction(() => document.querySelectorAll('.wb-node').length === 4);
  assert(await page.locator('[data-library="builtin-test"]').count() === 1, '노드 제거 후 서랍 기능 유지');
  await chooseNode('입력 노트');
  const text = ' 가 \n가\n나';
  await page.getByRole('textbox', { name: '실행 입력', exact: true }).fill(text);
  await page.getByRole('textbox', { name: '작업 묶음 이름' }).fill('서랍 복원 검사');
  await page.locator('.wb-toolbar select').selectOption(folderId);
  await click('서랍에 저장');
  await page.locator('.wb-message').filter({ hasText: 'v1' }).waitFor();
  assert(writes.filter(x => x === '/api/workbench/flows').length === 1, '작업 묶음 저장');
  await page.getByRole('textbox', { name: '실행 입력', exact: true }).fill('임시 편집');
  await page.locator('.wb-header').getByRole('button', { name: '진행판', exact: true }).click();
  await page.locator('.bd-nav').getByRole('button', { name: '기능 작업대', exact: true }).click();
  assert(await page.getByRole('textbox', { name: '실행 입력', exact: true }).inputValue() === '임시 편집', '닫기·재열기에서 입력 유지');
  await page.reload();
  await page.waitForFunction(() => typeof Data !== 'undefined' && Data.loaded);
  if (await page.locator('#workbench-screen').isHidden()) await page.locator('.bd-nav').getByRole('button', { name: '기능 작업대', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.wb-node').length === 4);
  assert(await page.getByRole('textbox', { name: '실행 입력', exact: true }).inputValue() === '임시 편집', '새로고침 후 브라우저 임시 흐름 복원');
  await drawer();
  await page.locator('.wb-drawer select').selectOption(folderId);
  await page.locator('.wb-library').getByRole('button', { name: '노트 보기·편집', exact: true }).click();
  await dialog('기능 노트 보기·편집').getByRole('textbox', { name: '앞에 붙일 글' }).fill('[새 버전] ');
  await dialog('기능 노트 보기·편집').getByRole('button', { name: '기능 저장', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('dialog'));
  assert((await page.locator('.wb-library small').textContent()).includes('v2'), '노트 편집은 새 버전으로 저장');
  assert((await page.locator(`[data-node="${customId}"]`).textContent()).includes('v1'), '기존 흐름은 꺼낸 당시 버전 유지');
  await page.locator('.wb-drawer').getByRole('button', { name: '작업 묶음', exact: true }).click();
  await page.locator('.wb-library').getByRole('button', { name: '불러오기', exact: true }).click();
  await dialog('작성 중인 흐름 바꾸기').getByRole('button', { name: '바꾸기', exact: true }).click();
  await chooseNode('입력 노트');
  assert(await page.getByRole('textbox', { name: '실행 입력', exact: true }).inputValue() === text.trim(), '서랍의 저장된 흐름 복원');
  assert(await page.locator('.wb-scope select').inputValue() === 'demo' && await page.locator('.wb-scope textarea').inputValue() === 'docs/**', '저장된 프로젝트·허용 범위 복원');
  await click('문서 내보내기');
  const exported = await dialog('작업 묶음 내보내기').getByRole('textbox').inputValue();
  assert(JSON.parse(exported).graph.nodes.length === 4, '흐름 문서 내보내기');
  await page.keyboard.press('Escape');
  assert(await page.getByRole('dialog').count() === 0, 'Escape로 닫기 · 초점 복귀');
  await click('문서 불러오기');
  await dialog('작업 묶음 불러오기').getByRole('textbox').fill('{');
  await dialog('작업 묶음 불러오기').getByRole('button', { name: '확인하고 불러오기', exact: true }).click();
  assert((await dialog('작업 묶음 불러오기').textContent()).includes('문서 형식'), '손상된 흐름 문서 거부');
  await dialog('작업 묶음 불러오기').getByRole('textbox').fill(exported);
  await dialog('작업 묶음 불러오기').getByRole('button', { name: '확인하고 불러오기', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('dialog'));
  assert(await page.locator('.wb-node').count() === 4, '검증 후 흐름 문서 불러오기');
  const movable = page.locator(`[data-node="${inputId}"]`);
  await movable.focus();
  const leftBefore = await movable.evaluate(el => el.offsetLeft);
  await page.keyboard.press('ArrowRight');
  assert(await movable.evaluate(el => el.offsetLeft) === leftBefore + 20, '키보드 방향키로 노드 이동');
  for (const [width, height] of [[1536, 960], [1024, 768], [800, 600], [390, 844]]) {
    await page.setViewportSize({ width, height });
    const g = await page.locator('#workbench-screen').evaluate(el => ({ width: el.clientWidth, scrollWidth: el.scrollWidth, height: el.clientHeight, scrollHeight: el.scrollHeight }));
    assert(g.scrollWidth <= g.width + 1, `${width}x${height}: 작업대 가로 넘침 없음`);
    geometry.push({ width, height, ...g });
    if (width === 390) await screenshot('small');
  }
  await page.setViewportSize({ width: 1536, height: 960 });
  await screenshot('graph');
  await click('실행 계획 확인');
  const planDialog = dialog('실행 전 계획 확인');
  assert((await planDialog.textContent()).includes('모델 호출 최대 0회'), '고정 처리의 모델 사용 0 표시');
  assert(!(await planDialog.locator('.wb-dialog-body').evaluate(e => [...e.childNodes].some(n => n.nodeType === Node.TEXT_NODE && n.textContent === 'null'))), '미사용 선택 영역에 null 글자 없음');
  assert(await planDialog.getByRole('button', { name: '확인한 계획 실행', exact: true }).isDisabled(), '확인 전 실행 잠금');
  await planDialog.getByRole('checkbox').check();
  let lostResponse = false;
  await page.route('**/api/workbench/start', async route => {
    if (!lostResponse) { await route.fetch(); lostResponse = true; return route.abort(); }
    return route.continue();
  });
  await planDialog.getByRole('button', { name: '확인한 계획 실행', exact: true }).click();
  await planDialog.locator('.wb-dialog-error').filter({ hasText: '연결이 끊겼' }).waitFor();
  assert(lostResponse, '서버 실행 후 응답 유실 상황 재현');
  await planDialog.getByRole('button', { name: '확인한 계획 실행', exact: true }).dblclick();
  await page.waitForFunction(() => document.querySelector('.wb-run-bar strong')?.textContent.startsWith('완료'));
  await page.unroute('**/api/workbench/start');
  let run = await readRun();
  assert((await page.evaluate(() => Data.workbenchGet('/ledger'))).runs.length === 1, '재전송·중복 클릭에도 실행 장부 한 개');
  assert(run.status === 'succeeded' && run.snapshot.max_model_calls === 0, '고정 처리 실제 완료');
  assert(Object.values(run.nodes).every(n => n.status === 'succeeded'), '실제 이벤트의 노드 상태 반영');
  assert(await page.locator('.wb-wire.s-succeeded').count() === 3, '실제 결과로 연결선 상태 표시');
  await chooseNode('반복 문장 노트');
  assert((await page.locator('.wb-detail pre').nth(1).textContent()).includes('[정리] 가\n나'), '노드별 입력·출력과 이전 버전 결과 조회');
  assert(run.snapshot.graph.nodes.find(n => n.id === customId).definition.version === 1, '실행 당시 노트·그래프 장부 보존');
  assert(await page.evaluate(() => Data.get().tasks.length) === 0, '고정 처리에서는 모델·작업 생성 없음');
  await screenshot('ledger');
  await click('내 작업대로 돌아가기');
  await replace('새 글 처리');
  await drawer();
  await page.locator('.wb-drawer').getByRole('button', { name: '기능', exact: true }).click();
  await page.locator('.wb-drawer select').selectOption('all');
  await page.getByRole('button', { name: '입력 조건 확인 꺼내기' }).click();
  await page.waitForFunction(() => document.querySelectorAll('.wb-node').length === 4);
  const conditionId = await page.locator('.wb-node[aria-pressed="true"]').getAttribute('data-node');
  await drawer(false);
  await page.getByRole('textbox', { name: '반드시 포함할 문구' }).fill('필수');
  const ids2 = await page.locator('.wb-node').evaluateAll(es => es.map(e => e.dataset.node));
  await page.getByRole('button', { name: `${ids2[1]}에서 ${ids2[2]} 연결 끊기` }).click();
  await page.getByRole('combobox', { name: '출발 노드' }).selectOption(ids2[1]);
  await page.getByRole('combobox', { name: '도착 노드' }).selectOption(conditionId);
  await click('연결하기');
  await page.getByRole('combobox', { name: '출발 노드' }).selectOption(conditionId);
  await page.getByRole('combobox', { name: '도착 노드' }).selectOption(ids2[2]);
  await click('연결하기');
  await chooseNode('입력 노트');
  await page.getByRole('textbox', { name: '실행 입력', exact: true }).fill('조건 누락');
  await click('실행 계획 확인');
  await dialog('실행 전 계획 확인').getByRole('checkbox').check();
  await dialog('실행 전 계획 확인').getByRole('button', { name: '확인한 계획 실행', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.wb-run-bar strong')?.textContent.startsWith('막힘'));
  run = await readRun();
  assert(run.nodes[conditionId].status === 'blocked' && run.nodes[ids2[2]].status === 'skipped', '조건 오류와 후속 노드 차단');
  await chooseNode('입력 조건 확인');
  assert((await page.locator('.wb-detail .wb-error').textContent()).includes('입력 조건'), '노드 오류·입력 조회');
  await click('기록 다시 확인');
  assert((await readRun()).status === 'blocked' && (await page.evaluate(() => Data.workbenchGet('/ledger'))).runs.length === 2, '실패복구는 기존 기록만 확인 · 재제출 없음');
  await screenshot('error');
  await click('내 작업대로 돌아가기');
  await replace('구현 묶음');
  await page.getByRole('textbox', { name: '실행 입력', exact: true }).fill('docs/answer.txt에 42를 저장해 주세요.');
  await chooseNode('구현');
  await page.getByRole('textbox', { name: '수용 기준 (한 줄에 하나)' }).fill('정답 파일 존재\n정답은 42');
  await click('기준별 완료 근거 지정');
  const evidenceDialog = dialog('기준별 완료 근거');
  await evidenceDialog.getByRole('textbox', { name: 'A1 필수 파일 경로' }).fill('docs/answer.txt');
  await evidenceDialog.getByRole('textbox', { name: 'A2 신뢰 검사 이름' }).fill('answer_is_42');
  await evidenceDialog.getByRole('button', { name: '근거 저장', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('dialog'));
  assert(await page.locator('.wb-assignee .face').count() === 1, '기존 직원 캐릭터를 담당 표시로 유지');
  await click('실행 계획 확인');
  const modelPlan = dialog('실행 전 계획 확인');
  assert((await modelPlan.textContent()).includes('모델 호출 최대 2회') && (await modelPlan.textContent()).includes('연습용 회사'), '기존 구현·검토 호출 상한과 가짜 회사 표시');
  await modelPlan.locator('[name="plan-confirm"]').check();
  assert(await modelPlan.getByRole('button', { name: '확인한 계획 실행', exact: true }).isDisabled(), '모델 허용 확인을 별도로 요구');
  await modelPlan.locator('[name="model-confirm"]').check();
  await modelPlan.getByRole('button', { name: '확인한 계획 실행', exact: true }).dblclick();
  await page.waitForFunction(() => document.querySelector('.wb-run-bar strong')?.textContent.startsWith('결재 대기'), null, { timeout: 90000 });
  run = await readRun();
  const build = run.snapshot.graph.nodes.find(n => n.definition.spec.operation === 'implement');
  assert(run.nodes[build.id].output.qa.verdict === 'pass', '기존 신뢰 검증 실제 통과');
  assert(run.nodes[build.id].output.review.verdict === 'approve', '기존 FakeRuntime 모델 리뷰 실제 통과');
  assert(run.nodes[build.id].output.runs.length === 2, '구현·검토 정확히 두 번 · 자동 재시도 없음');
  await chooseNode('사용자승인');
  await screenshot('approval');
  await click('기존 결재 창 열기');
  await page.waitForFunction(() => document.querySelector('#workbench-screen').hidden === true);
  assert(await page.locator('#layer-popup').isVisible(), '기존 결재 창으로 연결');
  const approval = page.getByRole('dialog', { name: '결재 · 구현', exact: true });
  await approval.getByRole('button', { name: '승인', exact: true }).click();
  await page.waitForFunction(id => Data.task(id)?.status === 'done', run.nodes[build.id].task);
  await page.keyboard.press('Escape');
  await page.locator('.bd-nav').getByRole('button', { name: '기능 작업대', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.wb-run-bar strong')?.textContent.startsWith('완료'));
  run = await readRun();
  const approved = run.snapshot.graph.nodes.find(n => n.definition.spec.operation === 'approve');
  assert(run.nodes[approved.id].output.merged_sha && run.status === 'succeeded', '기존 결재 UI에서 정확한 후보 병합');
  assert(Object.values(run.nodes).every(n => n.status === 'succeeded'), '승인 뒤 실제 이벤트로 후속 노드·장부 완료');
  assert(!(await page.locator('.wb-run-bar').evaluate(e => [...e.childNodes].some(n => n.nodeType === Node.TEXT_NODE && n.textContent === 'null'))), '완료 장부의 빈 행동 영역 표시 정상');
  assert(run.nodes[build.id].output.runs.length === 2, '완료 후 추가 모델 호출 없음');
  await screenshot('completed');
  assert(errors.length === 0, '브라우저 스크립트 오류 없음');
  return { status: 'pass', checks, count: checks.length, writes, geometry, screenshots, errors,
    environment: 'disposable company, actual Edge/UI/API, existing FakeRuntime/QA/approval', real_model_calls: 0, production_writes: 0,
    task: run.nodes[build.id].task, run: run.id };
}
